package org.opentaps.base.constants;

/*
 * Copyright (c) Open Source Strategies, Inc.
 *
 * Opentaps is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Opentaps is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Opentaps.  If not, see <http://www.gnu.org/licenses/>.
 */

// DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA CHANGE

/**
 * GlAccountClassTypeMap constant values.
 */
public final class GlAccountClassTypeMapConstants {

    private GlAccountClassTypeMapConstants() { }

    /** ACCOUNTS PAYABLE. */
    public static final String ACCOUNTS_PAYABLE = "ACCOUNTS_PAYABLE";
    /** ACCOUNTS RECEIVABLE. */
    public static final String ACCOUNTS_RECEIVABLE = "ACCOUNTS_RECEIVABLE";
    /** ASSET. */
    public static final String ASSET = "ASSET";
    /** BANK ACCOUNT. */
    public static final String BANK_STLMNT_ACCOUNT = "BANK_STLMNT_ACCOUNT";
    /** COGS. */
    public static final String COGS = "COGS";
    /** COMMISSION PAYABLE. */
    public static final String COMMISSIONS_PAYABLE = "COMMISSIONS_PAYABLE";
    /** CASH EQUIVALENT. */
    public static final String CURRENT_ASSET = "CURRENT_ASSET";
    /** CURRENT LIABILITY. */
    public static final String CURRENT_LIABILITY = "CURRENT_LIABILITY";
    /** ACCUM AMORTIZATION. */
    public static final String FIXED_ASSET = "FIXED_ASSET";
    /** INVENTORY. */
    public static final String INVENTORY_ACCOUNT = "INVENTORY_ACCOUNT";
    /** LIABILITY. */
    public static final String LIABILITY = "LIABILITY";
    /** LONG TERM LIABILITY. */
    public static final String LONG_TERM_LIABILITY = "LONG_TERM_LIABILITY";
    /** AMORTIZATION EXPENSE. */
    public static final String OPERATING_EXPENSE = "OPERATING_EXPENSE";
    /** INTEREST EXPENSE. */
    public static final String OTHER_EXPENSE = "OTHER_EXPENSE";
    /** CASH INCOME. */
    public static final String OTHER_INCOME = "OTHER_INCOME";
    /** EQUITY. */
    public static final String OWNERS_EQUITY = "OWNERS_EQUITY";
    /** RAW MATERIALS. */
    public static final String RAWMAT_INVENTORY = "RAWMAT_INVENTORY";
    /** REVENUE. */
    public static final String REVENUE = "REVENUE";
    /** TAX EXPENSE. */
    public static final String TAX_EXPENSE = "TAX_EXPENSE";
    /** WIP INVENTORY. */
    public static final String WIP_INVENTORY = "WIP_INVENTORY";

}
