package org.opentaps.domain.base.entities;

/*
* Copyright (c) 2008 - 2009 Open Source Strategies, Inc.
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the Honest Public License.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* Honest Public License for more details.
*
* You should have received a copy of the Honest Public License
* along with this program; if not, write to Funambol,
* 643 Bair Island Road, Suite 305 - Redwood City, CA 94063, USA
*/

// DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA MODEL CHANGES
// EXTEND THIS CLASS INSTEAD.

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import javolution.util.FastMap;

import org.opentaps.foundation.entity.Entity;
import org.opentaps.foundation.entity.EntityFieldInterface;
import org.opentaps.foundation.repository.RepositoryException;
import org.opentaps.foundation.repository.RepositoryInterface;
import javax.persistence.*;
import org.hibernate.search.annotations.*;
import java.lang.Long;
import java.lang.String;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * Auto generated base entity SurveyResponseAndAnswer.
 */
@javax.persistence.Entity
@NamedNativeQuery(name="selectSurveyResponseAndAnswers", query="SELECT SR.SURVEY_RESPONSE_ID AS \"surveyResponseId\",SR.SURVEY_ID AS \"surveyId\",SR.PARTY_ID AS \"partyId\",SR.RESPONSE_DATE AS \"responseDate\",SR.LAST_MODIFIED_DATE AS \"lastModifiedDate\",SR.REFERENCE_ID AS \"referenceId\",SR.GENERAL_FEEDBACK AS \"generalFeedback\",SR.ORDER_ID AS \"orderId\",SR.ORDER_ITEM_SEQ_ID AS \"orderItemSeqId\",SR.STATUS_ID AS \"statusId\",SRA.SURVEY_QUESTION_ID AS \"surveyQuestionId\",SRA.SURVEY_MULTI_RESP_COL_ID AS \"surveyMultiRespColId\",SRA.SURVEY_MULTI_RESP_ID AS \"surveyMultiRespId\",SRA.BOOLEAN_RESPONSE AS \"booleanResponse\",SRA.CURRENCY_RESPONSE AS \"currencyResponse\",SRA.FLOAT_RESPONSE AS \"floatResponse\",SRA.NUMERIC_RESPONSE AS \"numericResponse\",SRA.TEXT_RESPONSE AS \"textResponse\",SRA.SURVEY_OPTION_SEQ_ID AS \"surveyOptionSeqId\",SRA.CONTENT_ID AS \"contentId\",SRA.ANSWERED_DATE AS \"answeredDate\",SRA.AMOUNT_BASE AS \"amountBase\",SRA.AMOUNT_BASE_UOM_ID AS \"amountBaseUomId\",SRA.WEIGHT_FACTOR AS \"weightFactor\",SRA.DURATION AS \"duration\",SRA.DURATION_UOM_ID AS \"durationUomId\",SRA.SEQUENCE_NUM AS \"sequenceNum\" FROM SURVEY_RESPONSE SR INNER JOIN SURVEY_RESPONSE_ANSWER SRA ON SR.SURVEY_RESPONSE_ID = SRA.SURVEY_RESPONSE_ID", resultSetMapping="SurveyResponseAndAnswerMapping")
@SqlResultSetMapping(name="SurveyResponseAndAnswerMapping", entities={
@EntityResult(entityClass=SurveyResponseAndAnswer.class, fields = {
@FieldResult(name="surveyResponseId", column="surveyResponseId")
,@FieldResult(name="surveyId", column="surveyId")
,@FieldResult(name="partyId", column="partyId")
,@FieldResult(name="responseDate", column="responseDate")
,@FieldResult(name="lastModifiedDate", column="lastModifiedDate")
,@FieldResult(name="referenceId", column="referenceId")
,@FieldResult(name="generalFeedback", column="generalFeedback")
,@FieldResult(name="orderId", column="orderId")
,@FieldResult(name="orderItemSeqId", column="orderItemSeqId")
,@FieldResult(name="statusId", column="statusId")
,@FieldResult(name="surveyQuestionId", column="surveyQuestionId")
,@FieldResult(name="surveyMultiRespColId", column="surveyMultiRespColId")
,@FieldResult(name="surveyMultiRespId", column="surveyMultiRespId")
,@FieldResult(name="booleanResponse", column="booleanResponse")
,@FieldResult(name="currencyResponse", column="currencyResponse")
,@FieldResult(name="floatResponse", column="floatResponse")
,@FieldResult(name="numericResponse", column="numericResponse")
,@FieldResult(name="textResponse", column="textResponse")
,@FieldResult(name="surveyOptionSeqId", column="surveyOptionSeqId")
,@FieldResult(name="contentId", column="contentId")
,@FieldResult(name="answeredDate", column="answeredDate")
,@FieldResult(name="amountBase", column="amountBase")
,@FieldResult(name="amountBaseUomId", column="amountBaseUomId")
,@FieldResult(name="weightFactor", column="weightFactor")
,@FieldResult(name="duration", column="duration")
,@FieldResult(name="durationUomId", column="durationUomId")
,@FieldResult(name="sequenceNum", column="sequenceNum")
})})
@org.hibernate.annotations.Entity(mutable = false)
@org.hibernate.annotations.AccessType("field")
public class SurveyResponseAndAnswer extends Entity {
static {
java.util.Map<String, String> fields = new java.util.HashMap<String, String>();
        fields.put("surveyResponseId", "SR.SURVEY_RESPONSE_ID");
        fields.put("surveyId", "SR.SURVEY_ID");
        fields.put("partyId", "SR.PARTY_ID");
        fields.put("responseDate", "SR.RESPONSE_DATE");
        fields.put("lastModifiedDate", "SR.LAST_MODIFIED_DATE");
        fields.put("referenceId", "SR.REFERENCE_ID");
        fields.put("generalFeedback", "SR.GENERAL_FEEDBACK");
        fields.put("orderId", "SR.ORDER_ID");
        fields.put("orderItemSeqId", "SR.ORDER_ITEM_SEQ_ID");
        fields.put("statusId", "SR.STATUS_ID");
        fields.put("surveyQuestionId", "SRA.SURVEY_QUESTION_ID");
        fields.put("surveyMultiRespColId", "SRA.SURVEY_MULTI_RESP_COL_ID");
        fields.put("surveyMultiRespId", "SRA.SURVEY_MULTI_RESP_ID");
        fields.put("booleanResponse", "SRA.BOOLEAN_RESPONSE");
        fields.put("currencyResponse", "SRA.CURRENCY_RESPONSE");
        fields.put("floatResponse", "SRA.FLOAT_RESPONSE");
        fields.put("numericResponse", "SRA.NUMERIC_RESPONSE");
        fields.put("textResponse", "SRA.TEXT_RESPONSE");
        fields.put("surveyOptionSeqId", "SRA.SURVEY_OPTION_SEQ_ID");
        fields.put("contentId", "SRA.CONTENT_ID");
        fields.put("answeredDate", "SRA.ANSWERED_DATE");
        fields.put("amountBase", "SRA.AMOUNT_BASE");
        fields.put("amountBaseUomId", "SRA.AMOUNT_BASE_UOM_ID");
        fields.put("weightFactor", "SRA.WEIGHT_FACTOR");
        fields.put("duration", "SRA.DURATION");
        fields.put("durationUomId", "SRA.DURATION_UOM_ID");
        fields.put("sequenceNum", "SRA.SEQUENCE_NUM");
fieldMapColumns.put("SurveyResponseAndAnswer", fields);
}
  public static enum Fields implements EntityFieldInterface<SurveyResponseAndAnswer> {
    surveyResponseId("surveyResponseId"),
    surveyId("surveyId"),
    partyId("partyId"),
    responseDate("responseDate"),
    lastModifiedDate("lastModifiedDate"),
    referenceId("referenceId"),
    generalFeedback("generalFeedback"),
    orderId("orderId"),
    orderItemSeqId("orderItemSeqId"),
    statusId("statusId"),
    surveyQuestionId("surveyQuestionId"),
    surveyMultiRespColId("surveyMultiRespColId"),
    surveyMultiRespId("surveyMultiRespId"),
    booleanResponse("booleanResponse"),
    currencyResponse("currencyResponse"),
    floatResponse("floatResponse"),
    numericResponse("numericResponse"),
    textResponse("textResponse"),
    surveyOptionSeqId("surveyOptionSeqId"),
    contentId("contentId"),
    answeredDate("answeredDate"),
    amountBase("amountBase"),
    amountBaseUomId("amountBaseUomId"),
    weightFactor("weightFactor"),
    duration("duration"),
    durationUomId("durationUomId"),
    sequenceNum("sequenceNum");
    private final String fieldName;
    private Fields(String name) { fieldName = name; }
    /** {@inheritDoc} */
    public String getName() { return fieldName; }
    /** {@inheritDoc} */
    public String asc() { return fieldName + " ASC"; }
    /** {@inheritDoc} */
    public String desc() { return fieldName + " DESC"; }
  }

    @Id
   private String surveyResponseId;
    
   private String surveyId;
    
   private String partyId;
    
   private Timestamp responseDate;
    
   private Timestamp lastModifiedDate;
    
   private String referenceId;
    
   private String generalFeedback;
    
   private String orderId;
    
   private String orderItemSeqId;
    
   private String statusId;
    
   private String surveyQuestionId;
    
   private String surveyMultiRespColId;
    
   private String surveyMultiRespId;
    
   private String booleanResponse;
    
   private BigDecimal currencyResponse;
    
   private BigDecimal floatResponse;
    
   private Long numericResponse;
    
   private String textResponse;
    
   private String surveyOptionSeqId;
    
   private String contentId;
    
   private Timestamp answeredDate;
    
   private BigDecimal amountBase;
    
   private String amountBaseUomId;
    
   private BigDecimal weightFactor;
    
   private Long duration;
    
   private String durationUomId;
    
   private Long sequenceNum;
   @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
   @JoinColumn(name="SURVEY_ID", insertable=false, updatable=false)
   @org.hibernate.annotations.Generated(
      org.hibernate.annotations.GenerationTime.ALWAYS
   )
   
   private Survey survey = null;
   @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
   @JoinColumn(name="SURVEY_QUESTION_ID", insertable=false, updatable=false)
   @org.hibernate.annotations.Generated(
      org.hibernate.annotations.GenerationTime.ALWAYS
   )
   
   private SurveyQuestion surveyQuestion = null;
   private transient SurveyQuestionOption surveyQuestionOption = null;
   @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
   @JoinColumn(name="SURVEY_RESPONSE_ID", insertable=false, updatable=false)
   @org.hibernate.annotations.Generated(
      org.hibernate.annotations.GenerationTime.ALWAYS
   )
   
   private SurveyResponse surveyResponse = null;
   @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
   @JoinColumn(name="CONTENT_ID", insertable=false, updatable=false)
   @org.hibernate.annotations.Generated(
      org.hibernate.annotations.GenerationTime.ALWAYS
   )
   
   private Content content = null;
   private transient SurveyMultiRespColumn surveyMultiRespColumn = null;

  /**
   * Default constructor.
   */
  public SurveyResponseAndAnswer() {
      super();
      this.baseEntityName = "SurveyResponseAndAnswer";
      this.isView = true;
      
      this.primaryKeyNames = new ArrayList<String>();
      this.primaryKeyNames.add("surveyResponseId");this.primaryKeyNames.add("surveyQuestionId");this.primaryKeyNames.add("surveyMultiRespColId");
      this.allFieldsNames = new ArrayList<String>();
      this.allFieldsNames.add("surveyResponseId");this.allFieldsNames.add("surveyId");this.allFieldsNames.add("partyId");this.allFieldsNames.add("responseDate");this.allFieldsNames.add("lastModifiedDate");this.allFieldsNames.add("referenceId");this.allFieldsNames.add("generalFeedback");this.allFieldsNames.add("orderId");this.allFieldsNames.add("orderItemSeqId");this.allFieldsNames.add("statusId");this.allFieldsNames.add("surveyQuestionId");this.allFieldsNames.add("surveyMultiRespColId");this.allFieldsNames.add("surveyMultiRespId");this.allFieldsNames.add("booleanResponse");this.allFieldsNames.add("currencyResponse");this.allFieldsNames.add("floatResponse");this.allFieldsNames.add("numericResponse");this.allFieldsNames.add("textResponse");this.allFieldsNames.add("surveyOptionSeqId");this.allFieldsNames.add("contentId");this.allFieldsNames.add("answeredDate");this.allFieldsNames.add("amountBase");this.allFieldsNames.add("amountBaseUomId");this.allFieldsNames.add("weightFactor");this.allFieldsNames.add("duration");this.allFieldsNames.add("durationUomId");this.allFieldsNames.add("sequenceNum");
      this.nonPrimaryKeyNames = new ArrayList<String>();
      this.nonPrimaryKeyNames.addAll(allFieldsNames);
      this.nonPrimaryKeyNames.removeAll(primaryKeyNames);
  }

  /**
   * Constructor with a repository.
   * @param repository a <code>RepositoryInterface</code> value
   */
  public SurveyResponseAndAnswer(RepositoryInterface repository) {
      this();
      initRepository(repository);
  }

    /**
     * This is a view-entity, so the setter methods will be private to this class and for use in its fromMap constructor only
     */
    /**
     * Auto generated value setter.
     * @param surveyResponseId the surveyResponseId to set
     */
    public void setSurveyResponseId(String surveyResponseId) {
        this.surveyResponseId = surveyResponseId;
    }
    /**
     * Auto generated value setter.
     * @param surveyId the surveyId to set
     */
    public void setSurveyId(String surveyId) {
        this.surveyId = surveyId;
    }
    /**
     * Auto generated value setter.
     * @param partyId the partyId to set
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId;
    }
    /**
     * Auto generated value setter.
     * @param responseDate the responseDate to set
     */
    public void setResponseDate(Timestamp responseDate) {
        this.responseDate = responseDate;
    }
    /**
     * Auto generated value setter.
     * @param lastModifiedDate the lastModifiedDate to set
     */
    public void setLastModifiedDate(Timestamp lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    /**
     * Auto generated value setter.
     * @param referenceId the referenceId to set
     */
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }
    /**
     * Auto generated value setter.
     * @param generalFeedback the generalFeedback to set
     */
    public void setGeneralFeedback(String generalFeedback) {
        this.generalFeedback = generalFeedback;
    }
    /**
     * Auto generated value setter.
     * @param orderId the orderId to set
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    /**
     * Auto generated value setter.
     * @param orderItemSeqId the orderItemSeqId to set
     */
    public void setOrderItemSeqId(String orderItemSeqId) {
        this.orderItemSeqId = orderItemSeqId;
    }
    /**
     * Auto generated value setter.
     * @param statusId the statusId to set
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    /**
     * Auto generated value setter.
     * @param surveyQuestionId the surveyQuestionId to set
     */
    public void setSurveyQuestionId(String surveyQuestionId) {
        this.surveyQuestionId = surveyQuestionId;
    }
    /**
     * Auto generated value setter.
     * @param surveyMultiRespColId the surveyMultiRespColId to set
     */
    public void setSurveyMultiRespColId(String surveyMultiRespColId) {
        this.surveyMultiRespColId = surveyMultiRespColId;
    }
    /**
     * Auto generated value setter.
     * @param surveyMultiRespId the surveyMultiRespId to set
     */
    public void setSurveyMultiRespId(String surveyMultiRespId) {
        this.surveyMultiRespId = surveyMultiRespId;
    }
    /**
     * Auto generated value setter.
     * @param booleanResponse the booleanResponse to set
     */
    public void setBooleanResponse(String booleanResponse) {
        this.booleanResponse = booleanResponse;
    }
    /**
     * Auto generated value setter.
     * @param currencyResponse the currencyResponse to set
     */
    public void setCurrencyResponse(BigDecimal currencyResponse) {
        this.currencyResponse = currencyResponse;
    }
    /**
     * Auto generated value setter.
     * @param floatResponse the floatResponse to set
     */
    public void setFloatResponse(BigDecimal floatResponse) {
        this.floatResponse = floatResponse;
    }
    /**
     * Auto generated value setter.
     * @param numericResponse the numericResponse to set
     */
    public void setNumericResponse(Long numericResponse) {
        this.numericResponse = numericResponse;
    }
    /**
     * Auto generated value setter.
     * @param textResponse the textResponse to set
     */
    public void setTextResponse(String textResponse) {
        this.textResponse = textResponse;
    }
    /**
     * Auto generated value setter.
     * @param surveyOptionSeqId the surveyOptionSeqId to set
     */
    public void setSurveyOptionSeqId(String surveyOptionSeqId) {
        this.surveyOptionSeqId = surveyOptionSeqId;
    }
    /**
     * Auto generated value setter.
     * @param contentId the contentId to set
     */
    public void setContentId(String contentId) {
        this.contentId = contentId;
    }
    /**
     * Auto generated value setter.
     * @param answeredDate the answeredDate to set
     */
    public void setAnsweredDate(Timestamp answeredDate) {
        this.answeredDate = answeredDate;
    }
    /**
     * Auto generated value setter.
     * @param amountBase the amountBase to set
     */
    public void setAmountBase(BigDecimal amountBase) {
        this.amountBase = amountBase;
    }
    /**
     * Auto generated value setter.
     * @param amountBaseUomId the amountBaseUomId to set
     */
    public void setAmountBaseUomId(String amountBaseUomId) {
        this.amountBaseUomId = amountBaseUomId;
    }
    /**
     * Auto generated value setter.
     * @param weightFactor the weightFactor to set
     */
    public void setWeightFactor(BigDecimal weightFactor) {
        this.weightFactor = weightFactor;
    }
    /**
     * Auto generated value setter.
     * @param duration the duration to set
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }
    /**
     * Auto generated value setter.
     * @param durationUomId the durationUomId to set
     */
    public void setDurationUomId(String durationUomId) {
        this.durationUomId = durationUomId;
    }
    /**
     * Auto generated value setter.
     * @param sequenceNum the sequenceNum to set
     */
    public void setSequenceNum(Long sequenceNum) {
        this.sequenceNum = sequenceNum;
    }

    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyResponseId() {
        return this.surveyResponseId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyId() {
        return this.surveyId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getPartyId() {
        return this.partyId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getResponseDate() {
        return this.responseDate;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getReferenceId() {
        return this.referenceId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getGeneralFeedback() {
        return this.generalFeedback;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getOrderId() {
        return this.orderId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getOrderItemSeqId() {
        return this.orderItemSeqId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getStatusId() {
        return this.statusId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyQuestionId() {
        return this.surveyQuestionId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyMultiRespColId() {
        return this.surveyMultiRespColId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyMultiRespId() {
        return this.surveyMultiRespId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getBooleanResponse() {
        return this.booleanResponse;
    }
    /**
     * Auto generated value accessor.
     * @return <code>BigDecimal</code>
     */
    public BigDecimal getCurrencyResponse() {
        return this.currencyResponse;
    }
    /**
     * Auto generated value accessor.
     * @return <code>BigDecimal</code>
     */
    public BigDecimal getFloatResponse() {
        return this.floatResponse;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Long</code>
     */
    public Long getNumericResponse() {
        return this.numericResponse;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTextResponse() {
        return this.textResponse;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getSurveyOptionSeqId() {
        return this.surveyOptionSeqId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getContentId() {
        return this.contentId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getAnsweredDate() {
        return this.answeredDate;
    }
    /**
     * Auto generated value accessor.
     * @return <code>BigDecimal</code>
     */
    public BigDecimal getAmountBase() {
        return this.amountBase;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getAmountBaseUomId() {
        return this.amountBaseUomId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>BigDecimal</code>
     */
    public BigDecimal getWeightFactor() {
        return this.weightFactor;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Long</code>
     */
    public Long getDuration() {
        return this.duration;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getDurationUomId() {
        return this.durationUomId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Long</code>
     */
    public Long getSequenceNum() {
        return this.sequenceNum;
    }

    /**
     * Auto generated method that gets the related <code>Survey</code> by the relation named <code>Survey</code>.
     * @return the <code>Survey</code>
     * @throws RepositoryException if an error occurs
     */
    public Survey getSurvey() throws RepositoryException {
        if (this.survey == null) {
            this.survey = getRelatedOne(Survey.class, "Survey");
        }
        return this.survey;
    }
    /**
     * Auto generated method that gets the related <code>SurveyQuestion</code> by the relation named <code>SurveyQuestion</code>.
     * @return the <code>SurveyQuestion</code>
     * @throws RepositoryException if an error occurs
     */
    public SurveyQuestion getSurveyQuestion() throws RepositoryException {
        if (this.surveyQuestion == null) {
            this.surveyQuestion = getRelatedOne(SurveyQuestion.class, "SurveyQuestion");
        }
        return this.surveyQuestion;
    }
    /**
     * Auto generated method that gets the related <code>SurveyQuestionOption</code> by the relation named <code>SurveyQuestionOption</code>.
     * @return the <code>SurveyQuestionOption</code>
     * @throws RepositoryException if an error occurs
     */
    public SurveyQuestionOption getSurveyQuestionOption() throws RepositoryException {
        if (this.surveyQuestionOption == null) {
            this.surveyQuestionOption = getRelatedOne(SurveyQuestionOption.class, "SurveyQuestionOption");
        }
        return this.surveyQuestionOption;
    }
    /**
     * Auto generated method that gets the related <code>SurveyResponse</code> by the relation named <code>SurveyResponse</code>.
     * @return the <code>SurveyResponse</code>
     * @throws RepositoryException if an error occurs
     */
    public SurveyResponse getSurveyResponse() throws RepositoryException {
        if (this.surveyResponse == null) {
            this.surveyResponse = getRelatedOne(SurveyResponse.class, "SurveyResponse");
        }
        return this.surveyResponse;
    }
    /**
     * Auto generated method that gets the related <code>Content</code> by the relation named <code>Content</code>.
     * @return the <code>Content</code>
     * @throws RepositoryException if an error occurs
     */
    public Content getContent() throws RepositoryException {
        if (this.content == null) {
            this.content = getRelatedOne(Content.class, "Content");
        }
        return this.content;
    }
    /**
     * Auto generated method that gets the related <code>SurveyMultiRespColumn</code> by the relation named <code>SurveyMultiRespColumn</code>.
     * @return the <code>SurveyMultiRespColumn</code>
     * @throws RepositoryException if an error occurs
     */
    public SurveyMultiRespColumn getSurveyMultiRespColumn() throws RepositoryException {
        if (this.surveyMultiRespColumn == null) {
            this.surveyMultiRespColumn = getRelatedOne(SurveyMultiRespColumn.class, "SurveyMultiRespColumn");
        }
        return this.surveyMultiRespColumn;
    }

    /**
     * Auto generated value setter.
     * @param survey the survey to set
    */
    public void setSurvey(Survey survey) {
        this.survey = survey;
    }
    /**
     * Auto generated value setter.
     * @param surveyQuestion the surveyQuestion to set
    */
    public void setSurveyQuestion(SurveyQuestion surveyQuestion) {
        this.surveyQuestion = surveyQuestion;
    }
    /**
     * Auto generated value setter.
     * @param surveyQuestionOption the surveyQuestionOption to set
    */
    public void setSurveyQuestionOption(SurveyQuestionOption surveyQuestionOption) {
        this.surveyQuestionOption = surveyQuestionOption;
    }
    /**
     * Auto generated value setter.
     * @param surveyResponse the surveyResponse to set
    */
    public void setSurveyResponse(SurveyResponse surveyResponse) {
        this.surveyResponse = surveyResponse;
    }
    /**
     * Auto generated value setter.
     * @param content the content to set
    */
    public void setContent(Content content) {
        this.content = content;
    }
    /**
     * Auto generated value setter.
     * @param surveyMultiRespColumn the surveyMultiRespColumn to set
    */
    public void setSurveyMultiRespColumn(SurveyMultiRespColumn surveyMultiRespColumn) {
        this.surveyMultiRespColumn = surveyMultiRespColumn;
    }


    /** {@inheritDoc} */
    @Override
    public void fromMap(Map<String, Object> mapValue) {
        preInit();
        setSurveyResponseId((String) mapValue.get("surveyResponseId"));
        setSurveyId((String) mapValue.get("surveyId"));
        setPartyId((String) mapValue.get("partyId"));
        setResponseDate((Timestamp) mapValue.get("responseDate"));
        setLastModifiedDate((Timestamp) mapValue.get("lastModifiedDate"));
        setReferenceId((String) mapValue.get("referenceId"));
        setGeneralFeedback((String) mapValue.get("generalFeedback"));
        setOrderId((String) mapValue.get("orderId"));
        setOrderItemSeqId((String) mapValue.get("orderItemSeqId"));
        setStatusId((String) mapValue.get("statusId"));
        setSurveyQuestionId((String) mapValue.get("surveyQuestionId"));
        setSurveyMultiRespColId((String) mapValue.get("surveyMultiRespColId"));
        setSurveyMultiRespId((String) mapValue.get("surveyMultiRespId"));
        setBooleanResponse((String) mapValue.get("booleanResponse"));
        setCurrencyResponse(convertToBigDecimal(mapValue.get("currencyResponse")));
        setFloatResponse(convertToBigDecimal(mapValue.get("floatResponse")));
        setNumericResponse((Long) mapValue.get("numericResponse"));
        setTextResponse((String) mapValue.get("textResponse"));
        setSurveyOptionSeqId((String) mapValue.get("surveyOptionSeqId"));
        setContentId((String) mapValue.get("contentId"));
        setAnsweredDate((Timestamp) mapValue.get("answeredDate"));
        setAmountBase(convertToBigDecimal(mapValue.get("amountBase")));
        setAmountBaseUomId((String) mapValue.get("amountBaseUomId"));
        setWeightFactor(convertToBigDecimal(mapValue.get("weightFactor")));
        setDuration((Long) mapValue.get("duration"));
        setDurationUomId((String) mapValue.get("durationUomId"));
        setSequenceNum((Long) mapValue.get("sequenceNum"));
        postInit();
    }

    /** {@inheritDoc} */
    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> mapValue = new FastMap<String, Object>();
        mapValue.put("surveyResponseId", getSurveyResponseId());
        mapValue.put("surveyId", getSurveyId());
        mapValue.put("partyId", getPartyId());
        mapValue.put("responseDate", getResponseDate());
        mapValue.put("lastModifiedDate", getLastModifiedDate());
        mapValue.put("referenceId", getReferenceId());
        mapValue.put("generalFeedback", getGeneralFeedback());
        mapValue.put("orderId", getOrderId());
        mapValue.put("orderItemSeqId", getOrderItemSeqId());
        mapValue.put("statusId", getStatusId());
        mapValue.put("surveyQuestionId", getSurveyQuestionId());
        mapValue.put("surveyMultiRespColId", getSurveyMultiRespColId());
        mapValue.put("surveyMultiRespId", getSurveyMultiRespId());
        mapValue.put("booleanResponse", getBooleanResponse());
        mapValue.put("currencyResponse", getCurrencyResponse());
        mapValue.put("floatResponse", getFloatResponse());
        mapValue.put("numericResponse", getNumericResponse());
        mapValue.put("textResponse", getTextResponse());
        mapValue.put("surveyOptionSeqId", getSurveyOptionSeqId());
        mapValue.put("contentId", getContentId());
        mapValue.put("answeredDate", getAnsweredDate());
        mapValue.put("amountBase", getAmountBase());
        mapValue.put("amountBaseUomId", getAmountBaseUomId());
        mapValue.put("weightFactor", getWeightFactor());
        mapValue.put("duration", getDuration());
        mapValue.put("durationUomId", getDurationUomId());
        mapValue.put("sequenceNum", getSequenceNum());
        return mapValue;
    }


}
