package org.opentaps.base.entities;

/*
 * Copyright (c) 2008 - 2009 Open Source Strategies, Inc.
 *
 * Opentaps is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Opentaps is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Opentaps.  If not, see <http://www.gnu.org/licenses/>.
 */

// DO NOT EDIT THIS FILE!  THIS IS AUTO GENERATED AND WILL GET WRITTEN OVER PERIODICALLY WHEN THE DATA MODEL CHANGES
// EXTEND THIS CLASS INSTEAD.

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import javolution.util.FastMap;

import org.opentaps.foundation.entity.Entity;
import org.opentaps.foundation.entity.EntityFieldInterface;
import org.opentaps.foundation.repository.RepositoryException;
import org.opentaps.foundation.repository.RepositoryInterface;
import javax.persistence.*;
import org.hibernate.search.annotations.*;
import java.lang.String;
import java.sql.Timestamp;

/**
 * Auto generated base entity AcctgTagPostingCheck.
 */
@javax.persistence.Entity
@Table(name="ACCTG_TAG_POSTING_CHECK")
public class AcctgTagPostingCheck extends Entity {
static {
java.util.Map<String, String> fields = new java.util.HashMap<String, String>();
        fields.put("organizationPartyId", "ORGANIZATION_PARTY_ID");
        fields.put("tagEnum1MustBalance", "TAG_ENUM1_MUST_BALANCE");
        fields.put("tagEnum2MustBalance", "TAG_ENUM2_MUST_BALANCE");
        fields.put("tagEnum3MustBalance", "TAG_ENUM3_MUST_BALANCE");
        fields.put("tagEnum4MustBalance", "TAG_ENUM4_MUST_BALANCE");
        fields.put("tagEnum5MustBalance", "TAG_ENUM5_MUST_BALANCE");
        fields.put("tagEnum6MustBalance", "TAG_ENUM6_MUST_BALANCE");
        fields.put("tagEnum7MustBalance", "TAG_ENUM7_MUST_BALANCE");
        fields.put("tagEnum8MustBalance", "TAG_ENUM8_MUST_BALANCE");
        fields.put("tagEnum9MustBalance", "TAG_ENUM9_MUST_BALANCE");
        fields.put("tagEnum10MustBalance", "TAG_ENUM10_MUST_BALANCE");
        fields.put("lastUpdatedStamp", "LAST_UPDATED_STAMP");
        fields.put("lastUpdatedTxStamp", "LAST_UPDATED_TX_STAMP");
        fields.put("createdStamp", "CREATED_STAMP");
        fields.put("createdTxStamp", "CREATED_TX_STAMP");
fieldMapColumns.put("AcctgTagPostingCheck", fields);
}
  public static enum Fields implements EntityFieldInterface<AcctgTagPostingCheck> {
    organizationPartyId("organizationPartyId"),
    tagEnum1MustBalance("tagEnum1MustBalance"),
    tagEnum2MustBalance("tagEnum2MustBalance"),
    tagEnum3MustBalance("tagEnum3MustBalance"),
    tagEnum4MustBalance("tagEnum4MustBalance"),
    tagEnum5MustBalance("tagEnum5MustBalance"),
    tagEnum6MustBalance("tagEnum6MustBalance"),
    tagEnum7MustBalance("tagEnum7MustBalance"),
    tagEnum8MustBalance("tagEnum8MustBalance"),
    tagEnum9MustBalance("tagEnum9MustBalance"),
    tagEnum10MustBalance("tagEnum10MustBalance"),
    lastUpdatedStamp("lastUpdatedStamp"),
    lastUpdatedTxStamp("lastUpdatedTxStamp"),
    createdStamp("createdStamp"),
    createdTxStamp("createdTxStamp");
    private final String fieldName;
    private Fields(String name) { fieldName = name; }
    /** {@inheritDoc} */
    public String getName() { return fieldName; }
    /** {@inheritDoc} */
    public String asc() { return fieldName + " ASC"; }
    /** {@inheritDoc} */
    public String desc() { return fieldName + " DESC"; }
  }

   @org.hibernate.annotations.GenericGenerator(name="AcctgTagPostingCheck_GEN",  strategy="org.opentaps.foundation.entity.hibernate.OpentapsIdentifierGenerator")
   @GeneratedValue(generator="AcctgTagPostingCheck_GEN")
   @Id
   @Column(name="ORGANIZATION_PARTY_ID")
   private String organizationPartyId;
   @Column(name="TAG_ENUM1_MUST_BALANCE")
   private String tagEnum1MustBalance;
   @Column(name="TAG_ENUM2_MUST_BALANCE")
   private String tagEnum2MustBalance;
   @Column(name="TAG_ENUM3_MUST_BALANCE")
   private String tagEnum3MustBalance;
   @Column(name="TAG_ENUM4_MUST_BALANCE")
   private String tagEnum4MustBalance;
   @Column(name="TAG_ENUM5_MUST_BALANCE")
   private String tagEnum5MustBalance;
   @Column(name="TAG_ENUM6_MUST_BALANCE")
   private String tagEnum6MustBalance;
   @Column(name="TAG_ENUM7_MUST_BALANCE")
   private String tagEnum7MustBalance;
   @Column(name="TAG_ENUM8_MUST_BALANCE")
   private String tagEnum8MustBalance;
   @Column(name="TAG_ENUM9_MUST_BALANCE")
   private String tagEnum9MustBalance;
   @Column(name="TAG_ENUM10_MUST_BALANCE")
   private String tagEnum10MustBalance;
   @Column(name="LAST_UPDATED_STAMP")
   private Timestamp lastUpdatedStamp;
   @Column(name="LAST_UPDATED_TX_STAMP")
   private Timestamp lastUpdatedTxStamp;
   @Column(name="CREATED_STAMP")
   private Timestamp createdStamp;
   @Column(name="CREATED_TX_STAMP")
   private Timestamp createdTxStamp;
   @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.LAZY)
   @JoinColumn(name="ORGANIZATION_PARTY_ID", insertable=false, updatable=false)
   @org.hibernate.annotations.Generated(
      org.hibernate.annotations.GenerationTime.ALWAYS
   )
   
   private Party party = null;

  /**
   * Default constructor.
   */
  public AcctgTagPostingCheck() {
      super();
      this.baseEntityName = "AcctgTagPostingCheck";
      this.isView = false;
      
      this.primaryKeyNames = new ArrayList<String>();
      this.primaryKeyNames.add("organizationPartyId");
      this.allFieldsNames = new ArrayList<String>();
      this.allFieldsNames.add("organizationPartyId");this.allFieldsNames.add("tagEnum1MustBalance");this.allFieldsNames.add("tagEnum2MustBalance");this.allFieldsNames.add("tagEnum3MustBalance");this.allFieldsNames.add("tagEnum4MustBalance");this.allFieldsNames.add("tagEnum5MustBalance");this.allFieldsNames.add("tagEnum6MustBalance");this.allFieldsNames.add("tagEnum7MustBalance");this.allFieldsNames.add("tagEnum8MustBalance");this.allFieldsNames.add("tagEnum9MustBalance");this.allFieldsNames.add("tagEnum10MustBalance");this.allFieldsNames.add("lastUpdatedStamp");this.allFieldsNames.add("lastUpdatedTxStamp");this.allFieldsNames.add("createdStamp");this.allFieldsNames.add("createdTxStamp");
      this.nonPrimaryKeyNames = new ArrayList<String>();
      this.nonPrimaryKeyNames.addAll(allFieldsNames);
      this.nonPrimaryKeyNames.removeAll(primaryKeyNames);
  }

  /**
   * Constructor with a repository.
   * @param repository a <code>RepositoryInterface</code> value
   */
  public AcctgTagPostingCheck(RepositoryInterface repository) {
      this();
      initRepository(repository);
  }

    /**
     * Auto generated value setter.
     * @param organizationPartyId the organizationPartyId to set
     */
    public void setOrganizationPartyId(String organizationPartyId) {
        this.organizationPartyId = organizationPartyId;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum1MustBalance the tagEnum1MustBalance to set
     */
    public void setTagEnum1MustBalance(String tagEnum1MustBalance) {
        this.tagEnum1MustBalance = tagEnum1MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum2MustBalance the tagEnum2MustBalance to set
     */
    public void setTagEnum2MustBalance(String tagEnum2MustBalance) {
        this.tagEnum2MustBalance = tagEnum2MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum3MustBalance the tagEnum3MustBalance to set
     */
    public void setTagEnum3MustBalance(String tagEnum3MustBalance) {
        this.tagEnum3MustBalance = tagEnum3MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum4MustBalance the tagEnum4MustBalance to set
     */
    public void setTagEnum4MustBalance(String tagEnum4MustBalance) {
        this.tagEnum4MustBalance = tagEnum4MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum5MustBalance the tagEnum5MustBalance to set
     */
    public void setTagEnum5MustBalance(String tagEnum5MustBalance) {
        this.tagEnum5MustBalance = tagEnum5MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum6MustBalance the tagEnum6MustBalance to set
     */
    public void setTagEnum6MustBalance(String tagEnum6MustBalance) {
        this.tagEnum6MustBalance = tagEnum6MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum7MustBalance the tagEnum7MustBalance to set
     */
    public void setTagEnum7MustBalance(String tagEnum7MustBalance) {
        this.tagEnum7MustBalance = tagEnum7MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum8MustBalance the tagEnum8MustBalance to set
     */
    public void setTagEnum8MustBalance(String tagEnum8MustBalance) {
        this.tagEnum8MustBalance = tagEnum8MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum9MustBalance the tagEnum9MustBalance to set
     */
    public void setTagEnum9MustBalance(String tagEnum9MustBalance) {
        this.tagEnum9MustBalance = tagEnum9MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param tagEnum10MustBalance the tagEnum10MustBalance to set
     */
    public void setTagEnum10MustBalance(String tagEnum10MustBalance) {
        this.tagEnum10MustBalance = tagEnum10MustBalance;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedStamp the lastUpdatedStamp to set
     */
    public void setLastUpdatedStamp(Timestamp lastUpdatedStamp) {
        this.lastUpdatedStamp = lastUpdatedStamp;
    }
    /**
     * Auto generated value setter.
     * @param lastUpdatedTxStamp the lastUpdatedTxStamp to set
     */
    public void setLastUpdatedTxStamp(Timestamp lastUpdatedTxStamp) {
        this.lastUpdatedTxStamp = lastUpdatedTxStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdStamp the createdStamp to set
     */
    public void setCreatedStamp(Timestamp createdStamp) {
        this.createdStamp = createdStamp;
    }
    /**
     * Auto generated value setter.
     * @param createdTxStamp the createdTxStamp to set
     */
    public void setCreatedTxStamp(Timestamp createdTxStamp) {
        this.createdTxStamp = createdTxStamp;
    }

    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getOrganizationPartyId() {
        return this.organizationPartyId;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum1MustBalance() {
        return this.tagEnum1MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum2MustBalance() {
        return this.tagEnum2MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum3MustBalance() {
        return this.tagEnum3MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum4MustBalance() {
        return this.tagEnum4MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum5MustBalance() {
        return this.tagEnum5MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum6MustBalance() {
        return this.tagEnum6MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum7MustBalance() {
        return this.tagEnum7MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum8MustBalance() {
        return this.tagEnum8MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum9MustBalance() {
        return this.tagEnum9MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>String</code>
     */
    public String getTagEnum10MustBalance() {
        return this.tagEnum10MustBalance;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedStamp() {
        return this.lastUpdatedStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getLastUpdatedTxStamp() {
        return this.lastUpdatedTxStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedStamp() {
        return this.createdStamp;
    }
    /**
     * Auto generated value accessor.
     * @return <code>Timestamp</code>
     */
    public Timestamp getCreatedTxStamp() {
        return this.createdTxStamp;
    }

    /**
     * Auto generated method that gets the related <code>Party</code> by the relation named <code>Party</code>.
     * @return the <code>Party</code>
     * @throws RepositoryException if an error occurs
     */
    public Party getParty() throws RepositoryException {
        if (this.party == null) {
            this.party = getRelatedOne(Party.class, "Party");
        }
        return this.party;
    }

    /**
     * Auto generated value setter.
     * @param party the party to set
    */
    public void setParty(Party party) {
        this.party = party;
    }


    /** {@inheritDoc} */
    @Override
    public void fromMap(Map<String, Object> mapValue) {
        preInit();
        setOrganizationPartyId((String) mapValue.get("organizationPartyId"));
        setTagEnum1MustBalance((String) mapValue.get("tagEnum1MustBalance"));
        setTagEnum2MustBalance((String) mapValue.get("tagEnum2MustBalance"));
        setTagEnum3MustBalance((String) mapValue.get("tagEnum3MustBalance"));
        setTagEnum4MustBalance((String) mapValue.get("tagEnum4MustBalance"));
        setTagEnum5MustBalance((String) mapValue.get("tagEnum5MustBalance"));
        setTagEnum6MustBalance((String) mapValue.get("tagEnum6MustBalance"));
        setTagEnum7MustBalance((String) mapValue.get("tagEnum7MustBalance"));
        setTagEnum8MustBalance((String) mapValue.get("tagEnum8MustBalance"));
        setTagEnum9MustBalance((String) mapValue.get("tagEnum9MustBalance"));
        setTagEnum10MustBalance((String) mapValue.get("tagEnum10MustBalance"));
        setLastUpdatedStamp((Timestamp) mapValue.get("lastUpdatedStamp"));
        setLastUpdatedTxStamp((Timestamp) mapValue.get("lastUpdatedTxStamp"));
        setCreatedStamp((Timestamp) mapValue.get("createdStamp"));
        setCreatedTxStamp((Timestamp) mapValue.get("createdTxStamp"));
        postInit();
    }

    /** {@inheritDoc} */
    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> mapValue = new FastMap<String, Object>();
        mapValue.put("organizationPartyId", getOrganizationPartyId());
        mapValue.put("tagEnum1MustBalance", getTagEnum1MustBalance());
        mapValue.put("tagEnum2MustBalance", getTagEnum2MustBalance());
        mapValue.put("tagEnum3MustBalance", getTagEnum3MustBalance());
        mapValue.put("tagEnum4MustBalance", getTagEnum4MustBalance());
        mapValue.put("tagEnum5MustBalance", getTagEnum5MustBalance());
        mapValue.put("tagEnum6MustBalance", getTagEnum6MustBalance());
        mapValue.put("tagEnum7MustBalance", getTagEnum7MustBalance());
        mapValue.put("tagEnum8MustBalance", getTagEnum8MustBalance());
        mapValue.put("tagEnum9MustBalance", getTagEnum9MustBalance());
        mapValue.put("tagEnum10MustBalance", getTagEnum10MustBalance());
        mapValue.put("lastUpdatedStamp", getLastUpdatedStamp());
        mapValue.put("lastUpdatedTxStamp", getLastUpdatedTxStamp());
        mapValue.put("createdStamp", getCreatedStamp());
        mapValue.put("createdTxStamp", getCreatedTxStamp());
        return mapValue;
    }


}
